- name: This is our first play
  hosts: webserver1
  tasks:
    - name: "creat a new user on the machine"
      user:
         name: mytestuser2
         state: absent
         remove: yes   #This line will make sure that the homedirectory of the user also gets deleted. By default this option is No
