- name: This is our first play
  hosts: webserver1
  vars:
    age: 11

  tasks:
   - name: "creating file using variable"
     command: touch /tmp/18.txt
     when: age == 18

   - name: "creating file using variable"
     command: touch /tmp/greater_than_18.txt
     when: age > 18

   - name: "creating file using variable"
     command: touch /tmp/less_than_10.txt
     when: age < 10

   - name: "creating file using variable"
     command: touch /tmp/between_10_and_18.txt
     when: age > 10 and age < 18

   - name: "creating file using variable"
     command: touch /tmp/10_or_11.txt
     when: age == 10 or age == 11
