- name: This is our first play
  hosts: webserver1,sqlserver1
  strategy: free 
# In this both servers will not wait for each other to finish their tasks. As soon as task 1 is complete on server 1, it will start executing task2 and not wait for the server2 to complete # its task1 execution and vice versa.
  tasks:
    - name: "Install php on the webserver"
      yum: name=php state=present

    - name: "Install httpd on the webserver"
      yum: name=httpd state=present
