- name: This is our first play
  hosts: webserver1,sqlserver1,sql2,sql3,sql4,sql5.....................sql1000
  strategy: linear
  tasks:
    - name: "Install php on the webserver"
      yum: name=php state=present

    - name: "Install httpd on the webserver"
      yum: name=httpd state=present
