- name: this is first play
  hosts: webserver1
  tasks:
    - name: Exploring register
      command: hostname -s
      when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" ) or
            ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16" )
