- name: This is our first play
  hosts: webserver1
  tasks:

    - name: "set a fact"
      set_fact:
          our_fact: "Ansible Rocks!"
          ansible_distribution: "{{ ansible_distribution | upper }}"

    - name: "show custom fact"
      debug:
          msg: "{{ our_fact }}"

    - name: "show ansible distribution"
      debug:
          msg: "{{ ansible_distribution }}"
