- name: This is our first play
  hosts: webserver1
  tasks:
    - name: "Install php on the webserver"
      yum: name=php state=present

    - name: "Install httpd on the webserver"
      yum: name=httpd state=present

- name: This is our second play
  hosts: sqlserver1
  tasks:
    - name: "Install postgresql on the sqlserver"
      yum: name=postgresql state=present
