- name: this is first play
  hosts: webserver1
  vars:
    package_version: 1.2
  roles:
    - vars_testing

  tasks:
    - name: print package_version variable value
      vars:
        package_version: 1.4
      debug:
         msg: "{{ package_version }}"
