- name: This is our first play
  hosts: webserver1
  tasks:
    - name: "installing nginx"
      yum: 
        name: nginx
        state: present

    - name: "installing tree"
      yum:
        name: tree
        state: present
